### ISSUE TITLE
Sets user status offline

### ISSUE THREAD

**Issue by Coldvictory** [RayzrDev/SharpBot#100]
Whenever I run the bot it will switch my status to offline after a while?

**Comment by Rayzr522** [comment]
No. If you don't want to show as online all the time, you can use `//status invisible`. There's really no good solution to the status problem now that Discord changed how it handles user presence data.

**Comment by Coldvictory** [comment]
Oh sorry I dunno why I wrote it like that, having the bot running will cause my status to be set as offline after a while of being afk/inactive. This doesn't happen when the bot isn't running

**Comment by Rayzr522** [comment]
The bot doesn't/shouldn't do that. There's nothing in the code to explicitly do that, although I wonder if it's the `bot.user.setAFK(true);`. However, that was also the only solution to still allow mobile notifications when the bot was running.
