### ISSUE TITLE
Cannot quote messages globally

### ISSUE THREAD

**Issue by Blaui** [RayzrDev/SharpBot#102]
Whenever I attempt to quote a message from a different server or even a different channel, the bot simply pulls a different message from the current channel. Is this possible to be fixed?

**Comment by yonilerner** [comment]
The command currently just searches for messages in the current channel, since you can only fetch messages for a channel, not a server. The command *could* be expanded to allow other channels and server, but those extra arguments would have to be provided as part of the command I think

**Comment by Rayzr522** [comment]
Actually, the command already supports fetching from other channels. Make sure you're up to date, and you can specify by putting a space and then the channel's ID/mention after it.

**Comment by Blaui** [comment]
All right, thank you for that info! I recently updated the bot because of some issues with the `//userinfo` command and I didn't know that. 
What about quoting from user/Group DMs? This doesn't seem to be supported yet.

**Comment by Rayzr522** [comment]
There's a bug in it right now, I'll have to look into it. It's supposed to work.

**Comment by Rayzr522** [comment]
Patched in b798104.
