### ISSUE TITLE
Did everything right but no avail

### ISSUE THREAD

**Issue by ubscal** [RayzrDev/SharpBot#106]
I Did all the steps and it won't accept the token. All I get is an error.

**Comment by abyssvi** [comment]
What is the error you are getting?

**Comment by ubscal** [comment]
![image](https://user-images.githubusercontent.com/21148758/28747252-104740be-7460-11e7-82f9-6aaa31da4353.png)

**Comment by abyssvi** [comment]
Your token entered is incorrect. Please try the process again, be careful to make sure you enter the correct token.

**Comment by ubscal** [comment]
I entered the correct token. I did everything in the section you said to do.

**Comment by abyssvi** [comment]
You are receiving Error 4004 from Discord. You can see here in the Discord documentation that error 4004 occurs when "The account token sent with your identify payload is incorrect."

https://discordapp.com/developers/docs/topics/gateway#disconnections

I would log out of Discord, log back in, and try the entire process again. Perhaps try with the browser version of Discord. If you join the RayzrDev Discord server and PM me perhaps there's some other things we can try.
