### ISSUE TITLE
I have an issue with the `'userinfo` 

### ISSUE THREAD

**Issue by coolcalcacol** [RayzrDev/SharpBot#115]
Hi, I have an issue with the `'userinfo` then tagging me will show my status as offline, no matter what it actually is set as.

**Comment by coolcalcacol** [comment]
![image](https://user-images.githubusercontent.com/31094492/30037437-9e56723e-91b2-11e7-8eeb-f2a2df85132b.png)

**Comment by Rayzr522** [comment]
That's just a limit of Discord. The selfbot has no way of knowing your true status. It *should* show the proper value *if* you change your status via `//status`.

**Comment by coolcalcacol** [comment]
Aight, thanks
