### ISSUE TITLE
Binary Gulp Not found

### ISSUE THREAD

**Issue by Evan2-0** [RayzrDev/SharpBot#117]
When Doing yarn start Git said the binary gulp was not found how do I fix this issue?
 (exact error
     `$ yarn start
yarn run v1.1.0
$ gulp
error Couldn't find the binary gulp
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
` Thanks for your time please help me!

**Comment by Rayzr522** [comment]
You forgot to run `yarn install`. If you're on Windows, you need to run the `Install.bat` file in the SharpBot folder.
