### ISSUE TITLE
CAN'T START

### ISSUE THREAD

**Issue by carloverhamme** [RayzrDev/SharpBot#119]
I dit everything you said but the bot i not online on my server!

Plz help me

**Comment by Rayzr522** [comment]
This is a selfbot, not a normal bot. You need to give it *your* token, not the token of a normal bot. Please re-read the installation instructions. 

Also, please update to the latest version, because it should have told you that SharpBot cannot run on bot accounts when you tried to start the bot.

**Comment by gedaan2002** [comment]
It doesnt start for me to, I've used my own token and the run closes automaticly. I used git bash to download the bot files. it gives exit code 1.

**Comment by Rayzr522** [comment]
Did you install all the other dependencies? (node, yarn) 

Also, did you run the Install.bat file first?
