### ISSUE TITLE
Embed message

### ISSUE THREAD

**Issue by BananaHalla** [RayzrDev/SharpBot#120]
I actually don't know how to embed those messages... A Selfbot helps me to embed a message but I don't know how to edit a color for it... I mean the color of the side of the embedded message. It randoms each embedded messages.
![screenshot_536](https://user-images.githubusercontent.com/33493263/32561616-a40d9082-c4e7-11e7-8433-d29864367ff6.png)
A quick response would help me and I really appreciate it, thanks.

**Comment by Rayzr522** [comment]
Do `//help embed` for extended help with the embed command. All possible options and examples are provided in the help message.
