### ISSUE TITLE
Nodejs downloading background

### ISSUE THREAD

**Issue by BananaHalla** [RayzrDev/SharpBot#123]
I left the cmd opened for 10 mins when eating and when I came back, it ate up 150 mb ... I was like waaa?
So I'm asking on how to stop nodejs from downloading background when using the selfbot so it doesn't eat my data cuz I don't want my data to be used up. I want to do stuff like embedded messages and evals by leaving cmd opened.
 Thanks

**Comment by Rayzr522** [comment]
What do you mean it ate up 150mb? 150mb of memory, storage, or (internet) data?

**Comment by BananaHalla** [comment]
internet data.. is there any solution?

**Comment by Rayzr522** [comment]
I have no idea what in the world it would be doing that would use 150mb. How do you know it was SharpBot that was using that much data? I can't think of any possible way that it would use that much data, even if you left it running for a week, let alone 10 minutes.

**Comment by BananaHalla** [comment]
I'm using GlassWire application to track data usage and I think other selfbots also eat up lots of data cuz of node.js server-side javascript *downloading* background. Anyway thanks for replying.
![screenshot_548](https://user-images.githubusercontent.com/33493263/32774428-3af3d3b6-c967-11e7-86f7-088ebc7e67e9.png)

**Comment by Rayzr522** [comment]
I have no clue what that is, but there’s no way that SharpBot would use that much data. It simply doesn’t transfer anything large enough or fast enough ¯\_(ツ)_/¯

**Comment by BananaHalla** [comment]
Hmmm. I think I'll just leave it, maybe it's my laptop problem.. well thanks as the bot much helps me in Discord and mostly you as the dev.
