### ISSUE TITLE
What terminal are you using in the readme gif?

### ISSUE THREAD

**Issue by tegenton** [RayzrDev/SharpBot#129]

**Comment by Rayzr522** [comment]
> Warning: I'm using Linux, so if you aren't, you can't really use any of this :)

`gnome-terminal` (comes with the [Gnome DE](https://www.gnome.org)) with a patched version of CPMono_v07 as the font. It's using my system colors, which come from the [Adapta GTK theme](https://github.com/adapta-project/adapta-gtk-theme).

**Comment by tegenton** [comment]
Cool, thanks!
