### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by abyssvi** [RayzrDev/SharpBot#29]
A todo list managed through bot commands and stored in the database. Especially useful for myself ;)

**Comment by Rayzr522** [comment]
I was going to do this myself, but I'm happy to have you take a stab at it. After all, I _will_ be busy with #30.

**Comment by abyssvi** [comment]
No promises on the speed of it, but I have some ideas I definitely want to do with this. :)

**Comment by abyssvi** [comment]
Unassigning this from myself - anyone is free to do this if they'd like. :)

Things I'd like to see:
Ability to store multiple todo lists and switch between them (one is "active", command to switch which is active?)
Ability to strike-off items (not remove them).
Ability to delete items.

**Comment by yonilerner** [comment]
Claiming!

**Comment by yonilerner** [comment]
- Basic framework for optional features if config is provided
- Basic notification framework that notifies based on enabled features (the default option is console.log)
  - Add a notification option that uses a second bot to PM yourself

**Comment by yonilerner** [comment]
Adding notes from a different thread:
``The framework Ill be building will allow any manager, command, etc. to "register" a new optional config parameter, and then said manager, command, etc. would run if that config parameter was provided. So for a google image search command, in addition to the usual run and info exports, the file would also provide a configRequirements export, which would be an array of config names that the command requires to run. The command would only run if those requirements were met, and if they were, the run function would be passed a fourth argument consisting of a key/value map of all the config requirements for that command.

This is just an example of how it might work; I havent fully decided on implementation and interface yet.```

**Comment by Rayzr522** [comment]
Added in #93.
