### ISSUE TITLE
Random and funny outputs

### ISSUE THREAD

**Issue by LucasPMagno** [RayzrDev/SharpBot#32]
something like this:

https://cdn.discordapp.com/attachments/281141184108167178/305169127222280204/unknown.png
https://cdn.discordapp.com/attachments/281141184108167178/305169006950744066/unknown.png
https://cdn.discordapp.com/attachments/281141184108167178/305168920145428481/unknown.png

**Comment by Rayzr522** [comment]
@abyssvi what're your thoughts on this?

**Comment by abyssvi** [comment]
I'm not in favor of it for personal flavor reasons. I prefer consistent and obvious outputs. Worth noting that my usecase is largely utilitarian. 

This would probably be best handled by only doing it on silly/fun commands, and leaving the serious commands to be serious.

I'm a total grouch, I know xD

**Comment by Rayzr522** [comment]
There are much *much* better things to be done with SharpBot. I think this and #30 should be closed indefinitely.
