### ISSUE TITLE
Google Image search?

### ISSUE THREAD

**Issue by OnlinePlayer865** [RayzrDev/SharpBot#49]
Would it be possible to add a google image search function/command? Such as ```//gsearch pie```
and then have it pull up a few pie images. or something like that.

**Comment by abyssvi** [comment]
It's possible to allow for one image, but I think having it post more than one image would result in kinda spammy behavior - posting multiple posts in response to one post.

What do you think, @Rayzr522?

**Comment by JMccormick264** [comment]
Could it be kind of like the current google search? like maybe have 2 rows or 3 items each row? 2 down and 3 across?

**Comment by Rayzr522** [comment]
You can only show one image per embed. Showing multiple images would mean sending multiple embeds, and that's quite spammy.

**Comment by Baecon** [comment]
why dont you do it in a notsobot style where the reactions become a button to switch the picture, go back, or stop responding to reaction

**Comment by Baecon** [comment]
http://i.imgur.com/W9CsCCA.png

**Comment by Rayzr522** [comment]
Yes, that *is* a possibility. I believe @yonilerner is working on creating a system for giving people the option of providing a Google API key, allowing them to use commands that require the Google APIs.

**Comment by yonilerner** [comment]
The framework Ill be building will allow any manager, command, etc. to "register" a new optional config parameter, and then said manager, command, etc. would run if that config parameter was provided. So for a google image search command, in addition to the usual `run` and `info` exports, the file would also provide a `configRequirements` export, which would be an array of config names that the command requires to run. The command would only run if those requirements were met, and if they were, the `run` function would be passed a fourth argument consisting of a key/value map of all the config requirements for that command.

This is just an example of how it might work; I havent fully decided on implementation and interface yet.
