### ISSUE TITLE
[docs] Documentation for assistant bot

### ISSUE THREAD

**Issue by xshotD** [RayzrDev/SharpBot#79]
Pretty much the title. Was confusing on how to run, like I'm wondering, how does it work, etc.

**Comment by yonilerner** [comment]
Assistant bot is undocumented currently because its quite ready to be widely used; when its ready, it will be documented.

**Comment by yonilerner** [comment]
@Rayzr522 Please close this issue.

**Comment by xshotD** [comment]
No need, I can close it myself :p
