### ISSUE TITLE
Use Github Gist instead of hastebin for text uploads

### ISSUE THREAD

**Issue by yonilerner** [RayzrDev/SharpBot#81]
MINE!

**Comment by xshotD** [comment]
Is there any specific reason why though? Hastebin seems to work just fine to be honest.

**Comment by Rayzr522** [comment]
There is a size limit for Hastebin, but not for Gist. At least that's what @yonilerner tells me.

**Comment by xshotD** [comment]
Ah. May make sense, then

**Comment by yonilerner** [comment]
There is *definitely* a limit for hastebin.

**Comment by Rayzr522** [comment]
@yonilerner can this be closed now? 1c970c24c59b40a8665771f1cfe3f64fec02cdf9

**Comment by yonilerner** [comment]
Yup
