### ISSUE TITLE
//spotify results with HTTP 401

### ISSUE THREAD

**Issue by angeloanan** [RayzrDev/SharpBot#85]
When using //spotify with a link to a Spotify song, The result is an unauthorized error. The link I used is `https://open.spotify.com/track/1zxtt6Dx3cxEd45ICVsi32`.  

![What I typed + results](https://user-images.githubusercontent.com/2129163/27510737-e6a9d318-5941-11e7-816b-46dd9f75c2b9.png)

**Comment by Rayzr522** [comment]
@Doxylamin you set up the Spotify command, any ideas?

**Comment by Rayzr522** [comment]
Please make sure you're on the latest version of SharpBot (`//exec git pull`). I believe this was fixed a while back.

**Comment by xshotD** [comment]
Spotify API requires tokens for any request now.

My idea is that you should: do a OAuth thing with Spotify/find a way to generate these tokens

**Comment by Doxylamin** [comment]
I'm currently working on a rewrite with Client Credentials Flow. Therefore, no login would be needed.
Please give me some time. ETA 02.06.

**Comment by angeloanan** [comment]
@Rayzr522 Still returns with a 401 even after pulling from remote. 
![image](https://user-images.githubusercontent.com/2129163/27631778-ccd63fc8-5c23-11e7-96b6-346ceb704b7c.png)

**Comment by Doxylamin** [comment]
@angeloanan As I said, I am **currently** working on the rewrite. I'd expect an update at the 2nd of July.

**Comment by beezTEM** [comment]
Has this been resolved yet?

**Comment by Rayzr522** [comment]
@Doxylamin any updates on this? I neither use Spotify nor know how its APIs work, so I can't solve this myself.

**Comment by Doxylamin** [comment]
![grafik](https://user-images.githubusercontent.com/14816200/31446821-c50f7b2c-aea0-11e7-8788-011e44969461.png)
Working on it. 😛

**Comment by Rayzr522** [comment]
This issue isn't dead, it just needs #118 to be accepted, but I simply don't have the time to review and go through all the stylistic problems with the code right now.

**Comment by Rayzr522** [comment]
Added in #118 ✅
