### ISSUE TITLE
Bot not connecting

### ISSUE THREAD

**Issue by SomeUsername0361** [RayzrDev/SharpBot#89]
Hi, it doesnt put any problem, but the bot isnt connecting
![screenshot_1](https://user-images.githubusercontent.com/29817606/27762829-93bac9cc-5e79-11e7-8dc4-6719ffc9bf78.png)

**Comment by Rayzr522** [comment]
This is a selfbot, not a normal bot. You need to enter *your* client token. Do [these steps](https://github.com/RayzrDev/SharpBot#getting-your-user-token) inside of Discord to get your token.

**Comment by SomeUsername0361** [comment]
ok thanks it worked
