### ISSUE TITLE
Emails

### ISSUE THREAD

**Issue by Decyferable** [RayzrDev/SharpBot#99]
Not sure how or why the hell I am subscribed to this, but the unsubscribe doesn't work in the email. Any other options because I don't care about this project at all.

**Comment by yonilerner** [comment]
![image](https://user-images.githubusercontent.com/278810/28194258-f37b4e72-67f7-11e7-83ad-5189ea42e3e8.png)

![image](https://user-images.githubusercontent.com/278810/28194250-e6e75c46-67f7-11e7-8162-2a5e93df2311.png)

**Comment by Decyferable** [comment]
ty I never use github

**Comment by Decyferable** [comment]
Still getting emails could I be removed another way from this bs? Why was I added anyways to this email spam list?

**Comment by abyssvi** [comment]
GitHub controls who receives emails, not us. There's no mailing list. Check your settings, or make sure you've unwatched the repo (watching, by default, sends you emails of everything.)
